require: rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RescueModifier:
  Exclude:
    - test/**/*

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# only for ruby 2.3+
Style/SafeNavigation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Next:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - test/**/*

Style/Lambda:
  EnforcedStyle: literal

Style/WhileUntilModifier:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

# only for ruby 2.6+
Style/MapToHash:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

# we can not use new syntax for older rubies
Lint/ErbNewArguments:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - test/**/*

Naming/MethodParameterName:
  AllowedNames:
    - of
    - fk

Naming/AccessorMethodName:
  Exclude:
    - test/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false
