AllCops:
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RescueModifier:
  Exclude:
    - test/**/*

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics:
  Enabled: false
